<?php

trait TableMutationInspectionFilter
{

  protected $filter = [
    'no',
    'uuid',
    'uuid_belong_employee',
    'uuid_tb_inspection',
    'uuid_tb_location',
    'uuid_tb_equipment',
    // 'equipment_inspection',
    // 'location_inspection',
    'place_inspection',
    'condition_inspection',
    'grease_shoot_inspection',
    'weather_inspection',
    'temperature_inspection',
    'rain_inspection',
    'current_upnormal_inspection',
    'last_upnormal_inspection',
    'screenshoot_inspection',
    'created_at',
    'updated_at',

    'belong_employee.uuid',
    'belong_employee.name_employee',
    'belong_employee.position_employee',
    'belong_employee.nik_employee',
    'belong_employee.telpon_employee',
    'belong_employee.email_employee',
    'belong_employee.birth_place_employee',
    'belong_employee.birth_date_employee',
    'belong_employee.gender_employee',
    'belong_employee.marital_employee',
    'belong_employee.address_employee',
    'belong_employee.password_employee',
    'belong_employee.plain_password_employee',
    'belong_employee.photo_employee',
    'belong_employee.verification_employee',
    'belong_employee.disable_employee',
    'belong_employee.created_at',
    'belong_employee.updated_at',

    'belong_employees.uuid',
    'belong_employees.name_employee',
    'belong_employees.position_employee',
    'belong_employees.nik_employee',
    'belong_employees.telpon_employee',
    'belong_employees.email_employee',
    'belong_employees.birth_place_employee',
    'belong_employees.birth_date_employee',
    'belong_employees.gender_employee',
    'belong_employees.marital_employee',
    'belong_employees.address_employee',
    'belong_employees.password_employee',
    'belong_employees.plain_password_employee',
    'belong_employees.photo_employee',
    'belong_employees.verification_employee',
    'belong_employees.disable_employee',
    'belong_employees.created_at',
    'belong_employees.updated_at',

    'belong_library_location.uuid',
    'belong_library_location.label_location',
    'belong_library_location.name_location',
    'belong_library_location.created_at',
    'belong_library_location.updated_at',

    'belong_library_equipment.uuid',
    'belong_library_equipment.label_equipment',
    'belong_library_equipment.name_equipment',
    'belong_library_equipment.created_at',
    'belong_library_equipment.updated_at',

    'one_mutation_inspection_information.uuid',
    'one_mutation_inspection_information.uuid_tb_inspection',
    'one_mutation_inspection_information.uuid_tb_inspection.uuid_tb_employee',
    'one_mutation_inspection_information.label_inspection_information',
    'one_mutation_inspection_information.description_inspection_information',
    'one_mutation_inspection_information.created_at',
    'one_mutation_inspection_information.updated_at',

    'many_mutation_inspection.uuid',
    'many_mutation_inspection.uuid_belong_employee',
    'many_mutation_inspection.uuid_tb_inspection',
    'many_mutation_inspection.uuid_tb_location',
    'many_mutation_inspection.uuid_tb_equipment',
    // 'many_mutation_inspection.equipment_inspection',
    // 'many_mutation_inspection.location_inspection',
    'many_mutation_inspection.place_inspection',
    'many_mutation_inspection.condition_inspection',
    'many_mutation_inspection.grease_shoot_inspection',
    'many_mutation_inspection.weather_inspection',
    'many_mutation_inspection.temperature_inspection',
    'many_mutation_inspection.rain_inspection',
    'many_mutation_inspection.current_upnormal_inspection',
    'many_mutation_inspection.last_upnormal_inspection',
    'many_mutation_inspection.screenshoot_inspection',
    'many_mutation_inspection.created_at',
    'many_mutation_inspection.updated_at',

  ];

  public static function initialize()
  {
    return [
      'no'                            => '',
      'uuid'                          => '',
      'uuid_id_employee'              => '',
      'uuid_tb_inspection'            => '',
      'uuid_tb_location'              => '',
      'uuid_tb_equipment'             => '',
      // 'equipment_inspection'          => '',
      // 'location_inspection'           => '',
      'place_inspection'              => '',
      'condition_inspection'          => '',
      'grease_shoot_inspection'       => '',
      'weather_inspection'            => '',
      'temperature_inspection'        => '',
      'rain_inspection'               => '',
      'current_upnormal_inspection'   => '',
      'last_upnormal_inspection'      => '',
      'screenshoot_inspection'        => '',
      'created_at'                    => '',
      'updated_at'                    => '',
    ];
  }
}
