<?php

trait ViewReportFilter
{

  protected $filter = [
    'week',
    'year',
    'month',
    'month_name',
    'day',
    'day_name',
    'date',
    'time',
    'uuid',
    'uuid_tb_employee',
    'uuid_tb_location',
    'uuid_tb_equipment',
    'place_inspection',
    'avg_condition_inspection',
    'avg_grease_shoot_inspection',
    'avg_weather_inspection',
    'avg_temperature_inspection',
    'avg_rain_inspection',
    'current_upnormal_inspection',
    'last_upnormal_inspection',
    'screenshoot_inspection',
	'valid_inspection',
    'created_at',
    'updated_at',

    'tb_employee.uuid',
    'tb_employee.name_employee',
    'tb_employee.position_employee',
    'tb_employee.nik_employee',
    'tb_employee.telpon_employee',
    'tb_employee.email_employee',
    'tb_employee.birth_place_employee',
    'tb_employee.birth_date_employee',
    'tb_employee.gender_employee',
    'tb_employee.marital_employee',
    'tb_employee.address_employee',
    'tb_employee.password_employee',
    'tb_employee.plain_password_employee',
    'tb_employee.photo_employee',
    'tb_employee.verification_employee',
    'tb_employee.disable_employee',
    'tb_employee.created_at',
    'tb_employee.updated_at',

    'tb_employees.uuid',
    'tb_employees.name_employee',
    'tb_employees.position_employee',
    'tb_employees.nik_employee',
    'tb_employees.telpon_employee',
    'tb_employees.email_employee',
    'tb_employees.birth_place_employee',
    'tb_employees.birth_date_employee',
    'tb_employees.gender_employee',
    'tb_employees.marital_employee',
    'tb_employees.address_employee',
    'tb_employees.password_employee',
    'tb_employees.plain_password_employee',
    'tb_employees.photo_employee',
    'tb_employees.verification_employee',
    'tb_employees.disable_employee',
    'tb_employees.created_at',
    'tb_employees.updated_at',

    'tb_library_location.uuid',
    'tb_library_location.label_location',
    'tb_library_location.name_location',
    'tb_library_location.created_at',
    'tb_library_location.updated_at',

    'tb_library_equipment.uuid',
    'tb_library_equipment.label_equipment',
    'tb_library_equipment.name_equipment',
    'tb_library_equipment.created_at',
    'tb_library_equipment.updated_at',

  ];

  public static function initialize()
  {
    return [
      'week'                          => '',
      'year'                          => '',
      'month'                         => '',
      'month_name'                    => '',
      'day'                           => '',
      'day_name'                      => '',
      'date'                          => '',
      'time'                          => '',
      'uuid'                          => '',
      'uuid_tb_employee'              => '',
      'uuid_tb_location'              => '',
      'uuid_tb_equipment'             => '',
      'place_inspection'              => '',
      'avg_condition_inspection'      => '',
      'avg_grease_shoot_inspection'   => '',
      'avg_weather_inspection'        => '',
      'avg_temperature_inspection'    => '',
      'avg_rain_inspection'           => '',
      'current_upnormal_inspection'   => '',
      'last_upnormal_inspection'      => '',
      'screenshoot_inspection'        => '',
	  'valid_inspection'			  => '',
      'created_at'                    => '',
      'updated_at'                    => '',
    ];
  }
}
